### ISSUE TITLE
Add local variables at each backtrace line.

### ISSUE THREAD

**Issue by benarent** [airbrake/airbrake-python#21] opened 2015-02-16 19:29 UTC
Note: This is a question I got from Adam Easterling via Support.

-----
One thing that I frequently find myself wanting is a stack trace that  includes local variables at each stack frame. In Python, all that information is there -- however, it looks like your API doesn't have a place for this information.

I asked Codebase for your API documentation, and they directed me to version 2.3, https://help.airbrake.io/kb/api-2/notifier-api-version-23

```
*/notice/error/backtrace/line*

Required. This element can occur more than once. Each line element 
describes one code location or frame in the backtrace when the error 
occurred, and requires @file and @number attributes. If the location 
includes a method or function, the @method attribute should be used. 
```

Notice, there's not really a place to include local variables at each backtrace line. 

@vmihailenco Could we add this into V3? https://help.airbrake.io/kb/api-2/notifier-api-v3

**Comment by benarent** [comment] 2015-02-16 19:30
@gondoi What are your thoughts on this?

**Comment by gondoi** [comment] 2015-02-16 21:29
I'm going to have to look at @samstav on this one, since he has better exception knowledge than I do in Python.

**Comment by vmihailenco** [comment] 2015-02-17 14:00
I don't mind to extend API and update UI if there is a concrete suggestion.

**Comment by eastside** [comment] 2015-02-18 00:42
The concrete suggestion would be something like this. (I'm following the format on the API spec https://help.airbrake.io/kb/api-2/notifier-api-version-23)

> /notice/error/backtrace/line/var
> Optional. A list of variables and their value within a line of code in the backtrace. Each var element contains the printed value of variable, and requires the @name attribute, which is the name of the variable. Optional, @type, indicates the class or type of the variable.

For example, imagine you had the following Python script:
```
def foo():
    my_var = 123
    raise Exception
```

Here's the backtrace portion of the XML sent to airbrake...
```
<line file="path/to/foo.py" number="3" method="foo">
  <var name="my_var" type="int">123</var>
</line>
```

**Comment by dvdplm** [comment] 2015-02-18 11:42
I like this. :)

**Comment by samstav** [comment] 2015-02-18 17:47
ohai @dvdplm, we were at a rookie-o table together.

**Comment by benarent** [comment] 2015-02-18 17:59
I would propose that we add it to the V3 notifier API POST 


```
https://airbrake.io/api/v3/projects/PROJECT_ID/notices?key=API_KEY
Content-Type: application/json

{
  "notifier": {
    "name":    "notifier name",
    "version": "notifier version",
    "url":     "notifier url"
  },
  "errors": [
    {
      "type":      "error1",
      "message":   "message1",
      "backtrace": [
        {
          "file": "backtrace file",
          "line": 10,
          "function": "backtrace function"
        }
      ]
    },
    {
      "type":      "error2",
      "message":   "message2",
      "backtrace": [
        {
          "file": "backtrace file",
          "line": 10,
          "function": "backtrace function"
        }
      ]
    }
  ],
  "context": { // Optional.
    "os": "Linux 3.5.0-21-generic #32-Ubuntu SMP Tue Dec 11 18:51:59 UTC 2012 x86_64",
    "language": "Ruby 1.9.1",
    "environment": "production",
 
    "version": "1.1.1",
    "url:": "http://some-site.com/example",
    "rootDirectory": "/home/app-root-directory",
 
    "userId": "12345",
    "userName": "root",
    "userEmail": "root@root.com"
  },
  "environment": {}, // Optional.
  "session": {}, // Optional.
  "params": {} // Optional.
} ```

@samstav @vmihailenco I'll leave your thoughts on best way to modify the API.

**Comment by samstav** [comment] 2015-02-18 19:15
Is this an airbrake API issue/discussion, or airbrake python client?

I'll ensure that the python client makes it easy to pass any data the airbrake notifier API supports. What we have done with our project is include any relevant local variables in `'params'`, but it might be nice if there was a defined place for local variables. 

FWIW, I don't think it makes sense to add 'var' alongside file/line/function, since file/line/function is explicit and does a great job of defining a backtrace, because thats all that can be said, for certain, about a backtrace without runtime-specific information. Also, file/line/function/var would indicate that only one variable can be included per line... Alongside type/message/backtrace might make more sense, and even better if it were `'vars'` and it was an array of objects, with type/value/name ? 

Just throwing this out there:
```
...
 "errors": [
    {
      "vars": [{"name": "var1", "type": "int", "value": 3}, ...],
      "type":      "error1",
      "message":   "message1",
      "backtrace": [
        {
          "file": "backtrace file",
          "line": 10,
          "function": "backtrace function"
        }
      ]
    },
...
```

**Comment by benarent** [comment] 2015-02-18 19:30
@samstav Mostly it's an API question, if we should support it and how we should in the notifiers. It was a request from @eastside . I'll let him share his thoughts on this proposed idea.

**Comment by samstav** [comment] 2015-02-18 19:33
Ok, cool. Thanks @benarent

**Comment by eastside** [comment] 2015-02-18 21:47
Yep, I'd say this is definitely an API question/issue. Also, my apologies for my previous post. I'm looking at it now and realizing that it's woefully incomplete. Also, ah, I see that v3 of the API uses JSON: Apologies for using XML in my example.

@samstav, in your proposed scheme, would it not make more sense for the "vars" key to be part of the "backtrace" object? To be clear, it would look like the following...

```
...
 "errors": [
    {
      "type":      "error1",
      "message":   "message1",
      "backtrace": [
        {
          "file": "backtrace file",
          "line": 10,
          "function": "backtrace function",
          "vars": [{"name": "var1", "type": "int", "value": 3}, ...],
        }
      ]
    },
...
```

After all, the idea here is that each frame of the stack has local variables. So shouldn't it be part of the "backtrace" object?

**Comment by samstav** [comment] 2015-02-19 01:01
@eastside good point. That could be a fun problem to solve for some clients. For python, I guess we would just use the [`inspect` module](https://docs.python.org/2/library/inspect.html) to look up the local variables at each item in the stackframe.

**Comment by dvdplm** [comment] 2015-02-19 08:26
I think that extracting the local context for each frame is probably overkill; maybe we can limit this to the top-most frame? Also, airbrake will reject payloads above 64k, and it's easy to imagine how including local vars and their values can make the payload balloon in size. I'd consider avoiding sending anything but small strings, ints, and floats.

**Comment by eastside** [comment] 2015-02-19 19:57
Would it really be overkill? Haven't we all encountered a bug in production, usually a type error of some kind, where you look at the trace and you're like, "I have no idea how this even happened." And it's one of those errors that occurs rarely, under particular circumstances, and is therefore difficult to reproduce. (It is in part difficult to reproduce because the conditions of the error are hidden!)

It is in those instances when I wish I had more clues. If I had the locals at each stack frame, it might clue me in on what the real issue is. In fact, just as I was in the middle of writing this, one of my coworkers asked me about a bug. We use a service's API, and it's giving a weird error for one particular user -- just one, not any of the other millions of users we have. There's a variable two frames down from where the error is raised that I wish I had the value of, but I don't.

I agree, however, that the size of the payload is a concern. Perhaps we could do something like, truncate the rendered string of a variable if it is too long. For example, if you have a variable which is a 10 KB string, we only print the first 30 characters. That sort of thing.

In any case, it could be up to the individual project/application to decide how they might curtail what information is sent. Modifying the API to accept local variables on each stack frame would be a prerequisite step.

**Comment by phumpal** [comment] 2015-12-19 01:09
Closing for now as there's been no follow up for 10 months.

Please feel free reopen if  still an issue.

**Closed by phumpal** 2015-12-19 01:09 UTC

**Comment by boxed** [comment] 2021-04-13 08:06
Found this while googling how to get local variables. To me the tool is pretty much worthless without this. Certainly it can't compete with Sentry which has it.

**Comment by djsmith42** [comment] 2021-12-23 19:03
I agree this is extremely useful. I used this feature in Sentry regularly, for years. But Airbrake (still) doesn't have it? When a function throws `ArgumentError` or when code misbehaves, it's extremely value to see what argument **values** caused the issue. Without this, we are left guessing.
